project:
  type: book
  
execute:
  freeze: auto

book:
  title: "Pip Technical Guidelines"
  author:
    - R.Andres Castenada
    - Ronak Shah
  date: "8/3/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - code_coverage.qmd
    - github_actions.qmd
    - Increase_performance_WB_laptop.qmd
    - setupR.qmd
    - interact_vm.qmd
    - VScode_Setup_for_stata.qmd
    - VScode_setup_for_github.qmd
    - copilot_protocols_guidelines.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: css/tachyons.css
  pdf:
    documentclass: scrreprt

editor: visual
