project:
  type: book

preview:
 host: 127.0.0.1
 port: 8081
 browser: false

execute:
  freeze: auto

book:
  title: "Pip Technical Guidelines"
  author:
    - R.Andres Castenada
    - Ronak Shah
  date: today
  chapters:
    - index.qmd
    - part: "R Setup and efficiency"
      chapters:
        - setupR.qmd
    - part: "VSCode Setup"
      chapters:
        - VScode_Setup_for_stata.qmd
        - VScode_setup_for_github.qmd
    - part: "Copilot and AI Tools"
      chapters:
        - copilot_protocols.qmd
        - copilot_guidelines.qmd
    - part: "MISC Tools and Tips"
      chapters:
        - code_coverage.qmd
        - github_actions.qmd
        - Increase_performance_WB_laptop.qmd
        - interact_vm.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: css/tachyons.css
  pdf:
    documentclass: scrreprt

editor: source
